spring.application.name=notification-service
server.port=0

## Discovery server
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:password@localhost:8761/eureka}

## Distributed tracing properties
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

## Kafka configs
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=event:com.clasher.notification_service.OrderPlacedEvent

## Logging
logging.level.root=ERROR
logging.level.com.clasher.notification_service=INFO
logging.level.org.springframework=ERROR
logging.level.org.apache.kafka=ERROR
logging.level.kafka=ERROR
logging.level.com.netflix.discovery=ERROR
logging.level.zipkin2=ERROR
spring.main.banner-mode=off
